export const uiText = {
  onboarding: {
    title: 'Get Started',
    description: 'Set up your workspace and start building a Prospect pipeline.',
    heroBadge: 'Live Route Planning',
    heroHeading: 'Build a sharper field day with real businesses, Routes, and Follow-Ups that stick.',
    heroDescription:
      'RepRoute remembers your real Prospects, Saved Prospects, Route stops, notes, priorities, and Follow-Up dates between visits.',
    metrics: {
      realProspectsLoaded: 'Real Prospects Loaded',
      savedProspects: 'Saved Prospects',
      routeStops: 'Route Stops',
      followUpsDue: 'Follow-Ups Due',
    },
    actions: {
      findProspects: 'Find Prospects',
      viewRoute: 'View Route',
    },
    startHereEyebrow: 'Start Here',
    searchStatusEyebrow: 'Live Search Status',
    realProspectsDetail: 'Live Google Places businesses currently stored on this device.',
    catalogSummary:
      'Saved Prospects, Route stops, and Follow-Ups all come from live Google Places searches.',
    upcomingFollowUpsDetail: (count: number) => `${count} scheduled in the next seven days`,
    storedProspectsSummary: (count: number) => `${count} real businesses stored locally`,
    hotTargetsEyebrow: 'Best Nearby Opportunities',
    hotTargetsHeading: 'Hot Targets',
    nextFollowUp: 'Next Follow-Up',
    hotTargetsEmptyAction: 'Open Search',
  },
  navigation: {
    appName: 'RepRoute',
    tagline: 'Field Sales Route Planner',
    liveBadge: 'Live Google Places',
    primaryNavAriaLabel: 'Primary',
    themeToggleAriaLabel: 'Toggle color theme',
    items: {
      dashboard: 'Home',
      map: 'Route',
      search: 'Search',
      saved: 'Saved',
      followUps: 'Follow-Ups',
      settings: 'Settings',
    },
    screenMeta: {
      dashboard: {
        title: 'Territory Command',
        subtitle:
          'Search real businesses with Google Places and keep your Route activity saved locally.',
      },
      map: {
        title: 'Today’s Route',
        subtitle:
          'Review your stops, navigate the day, and work through Route activity from one screen.',
      },
      search: {
        title: 'Prospect Search',
        subtitle:
          'Search live Google Places by keyword and market, then save the best Prospects or add them to a Route.',
      },
      saved: {
        title: 'Saved Prospects',
        subtitle:
          'Keep high-fit Prospects ready for future Route days, follow-up work, and CRM export.',
      },
      'follow-ups': {
        title: 'Follow-Ups',
        subtitle: 'Track every scheduled Follow-Up in one mobile-friendly workspace.',
      },
      settings: {
        title: 'Settings',
        subtitle: 'Manage Google Places, CRM Export, backups, and workspace preferences.',
      },
    },
    accountMenu: {
      ariaLabel: 'Open profile menu',
      settings: 'Settings',
      exportCrm: 'Export CRM Data',
      backup: 'Backup Data',
      signIn: 'Sign In',
      signInPlaceholder:
        'Sign in is coming soon. This account menu is ready for future authentication.',
      workspaceTitle: 'RepRoute Workspace',
      workspaceDescription:
        'No account is connected yet. This profile area is ready for future sign-in support.',
    },
    travelMode: {
      label: 'Travel mode',
      driving: 'Driving',
      walking: 'Walking',
    },
  },
  search: {
    eyebrow: 'Google Places First',
    heading: 'Find Real Prospects',
    prominentTitle: 'Find real prospects',
    prominentDescription:
      'Search live Google Places by keyword and city, then save qualified Prospects or add them to a Route.',
    keywordLabel: 'Keyword',
    keywordPlaceholder: 'equipment rental',
    locationLabel: 'City or market',
    locationPlaceholder: 'Austin, TX',
    searchButton: 'Search Google Places',
    searchingButton: 'Searching Google Places...',
    suggestedSearchesLabel: 'Suggested Searches',
    suggestedKeywords: [
      'equipment rental',
      'pipeline operators',
      'natural gas companies',
      'oilfield services',
      'industrial supply',
      'HVAC contractors',
      'electrical contractors',
      'plumbing contractors',
      'construction companies',
    ],
    priorityFilterLabel: 'Priority Filter',
    priorityOptions: ['All', 'Hot', 'Warm', 'Cold'] as const,
    statusHeading: 'Live Search Status',
    catalogHeading: 'Google Places Catalog',
    resultsEyebrow: 'Live Results',
    resultsHeading: 'Search Results',
    testButton: 'Test',
    openSettings: 'Open settings',
    statusMessages: {
      liveResults: (count: number, query: string) =>
        `Live Google Places returned ${count} result${count === 1 ? '' : 's'} for “${query}”.`,
      noLiveResults: (query: string) => `Google Places returned no live results for “${query}”.`,
    },
    summary: {
      results: (count: number) => `${count} live Google Places result${count === 1 ? '' : 's'}`,
      error: 'Google Places error',
      resultsReturned: (count: number) => `${count} result${count === 1 ? '' : 's'} returned.`,
    },
    card: {
      badge: 'Live Google Places',
      searchResult: 'Search Result',
      save: 'Save Prospect',
      saved: 'Saved Prospect',
      removeSaved: 'Remove Saved Prospect',
      addToRoute: 'Add to Route',
      inRoute: 'In Route',
      removeRoute: 'Remove from Route',
      openInMaps: 'Open in Google Maps',
      navigateDrive: 'Navigate Drive',
      navigateWalk: 'Navigate Walk',
    },
    prospectCard: {
      removeFromSavedAria: 'Remove from Saved Prospects',
      saveProspectAria: 'Save Prospect',
      followUpPrefix: 'Follow-Up',
      notes: 'Notes',
      nextTouch: 'Next Touch',
      removeRoute: 'Remove from Route',
      manage: 'Manage',
      hide: 'Hide',
      priority: 'Priority',
      followUpDate: 'Follow-Up Date',
      clear: 'Clear',
      prospectNotes: 'Prospect Notes',
      editorHint: 'Edits save instantly to local storage on this device.',
    },
  },
  saved: {
    eyebrow: 'Saved Pipeline',
    heading: 'Saved Prospects',
    countLabel: (count: number) => `${count} saved`,
    summaryPrimaryTitle: 'Keep the bench warm',
    summaryPrimaryDescription:
      'Saved Prospects stay available even when they are not on today’s Route.',
    summarySecondaryTitle: 'Notes stay attached',
    summarySecondaryDescription:
      'Every note, priority, and Follow-Up date is stored locally for future visits.',
    emptyAction: 'Browse Prospects',
  },
  routes: {
    suggestedKeywordCta: 'Find real prospects',
    routeSnapshotEyebrow: 'Today’s Route',
    routeSnapshotHeading: 'Route Snapshot',
    openRoute: 'Open Route',
    routeMapEyebrow: 'Live Route Map',
    routeMapHeading: 'Route Map',
    routeMapDescription:
      'Search results, Saved Prospects, and Route stops stay visible on the map while you work the day.',
    currentLocation: 'Your current location',
    todayListSummary: (count: number) => `${count} stops in today’s list`,
    navigateEntireRoute: 'Navigate Entire Route',
    clearRoute: 'Clear Route',
    mapSummary: {
      searchResults: (count: number) => `${count} search results`,
      savedProspects: (count: number) => `${count} Saved Prospects`,
      routeStops: (count: number) => `${count} Route stops`,
      visiblePins: (count: number) => `${count} visible pins`,
      routeMiles: (miles: string) => `${miles} total Route miles`,
      nearbySuggestions: (count: number) => `${count} nearby suggestions`,
    },
    stats: {
      routeStopsLabel: 'Today’s Route',
      routeStopsDetail: (miles: string) => `${miles} currently loaded into the Route`,
      completedStops: 'Completed Stops',
      completedStopsDetail: (remaining: number) => `${remaining} remaining on today’s Route`,
      estimatedDriveTime: 'Estimated Drive Time',
      estimatedDriveTimeDetail: (miles: string) => `${miles} currently planned`,
      completion: 'Completion',
      completionDetail: 'Progress across the active Route',
      nearbyProspects: 'Nearby Prospects',
      nearbyProspectsDetail: 'Within 5 miles of the current Route',
    },
    fieldWorkflowEyebrow: 'Field Workflow',
    fieldWorkflowHeading: 'Today’s Route',
    routeReady: 'Route ready',
    nextStop: (businessName: string) => `Next: ${businessName}`,
    currentFocusTitle: 'Current Focus',
    routeStopInfo: (order?: number) => `Route stop ${order ?? ''}`.trim(),
    stopLabel: (index: number) => `Stop ${index + 1}`,
    completed: 'Completed',
    markStopCompleteAria: 'Mark stop complete',
    markStopIncompleteAria: 'Mark stop incomplete',
    reorderStopAria: 'Reorder stop',
    actions: {
      callBusiness: 'Call Business',
      openWebsite: 'Open Website',
      navigateDrive: 'Navigate Drive',
      navigateWalk: 'Navigate Walk',
      remove: 'Remove',
      addNearbyProspect: 'Add Nearby Prospect',
      addToRoute: 'Add to Route',
    },
    visitOutcomeLabel: 'Visit Outcome',
    quickNoteLabel: 'Quick Note After Visit',
    quickNotePlaceholder: 'Capture what happened at this stop...',
    nearbyEyebrow: 'Nearby Coverage',
    nearbyHeading: 'Nearby Prospects',
    withinFiveMiles: 'Within 5 Miles',
    nearbyDistanceLabel: (distance: number) => `${distance.toFixed(1)} mi from Route`,
    outcomeTags: [
      'No Answer',
      'Decision Maker Met',
      'Follow-Up Needed',
      'Quote Opportunity',
      'Not Interested',
    ] as const,
  },
  followUps: {
    noDate: 'No Follow-Up set',
    stats: {
      scheduled: 'Scheduled Follow-Ups',
      scheduledDetail: 'Every Follow-Up currently tracked on this device',
      dueNow: 'Due Now',
      dueNowDetail: 'Prospects that should be touched today or earlier',
      thisWeek: 'This Week',
      thisWeekDetail: 'Follow-Ups due within the next seven days',
    },
    openProspect: 'Open Prospect',
    savedStatus: 'Saved Prospect',
    unsavedStatus: 'Unsaved Prospect',
    nextFollowUp: 'Next Follow-Up',
    statuses: {
      dueNow: 'Due Now',
      tomorrow: 'Tomorrow',
      thisWeek: 'This Week',
      later: 'Later',
    },
  },
  settings: {
    appearanceTitle: 'Appearance',
    appearanceDescription: 'Switch between dark and light workspace themes.',
    darkMode: 'Dark mode',
    lightMode: 'Light mode',
    googlePlacesEyebrow: 'Google Places',
    googlePlacesHeading: 'Connection Test',
    apiKeyDetected: 'API key detected',
    apiKeyMissing: 'API key missing',
    googlePlacesDescription:
      'Run a live test search for “equipment rental Austin TX” to confirm results are loading.',
    testConnectionButton: 'Test Google Places Connection',
    resultsReturned: (count: number) => `Results returned: ${count}`,
    errorDetails: (details: string) => `Error details: ${details}`,
    storageEyebrow: 'Storage Status',
    storageHeading: 'Local-First Data',
    storageLocalTitle: 'Saved locally',
    storageLocalDescription:
      'Real Prospects, Saved Prospects, Route stops, notes, priorities, and dates stay on this device.',
    storageLiveTitle: 'Live search only',
    storageLiveDescription:
      'RepRoute relies on Google Places for real business discovery and does not use fallback business data.',
    backupEyebrow: 'Data Backup',
    backupHeading: 'Data Backup',
    backupDescription:
      'Export a JSON snapshot of your local RepRoute data, or preview a backup before replacing current data on this device.',
    unknownExportDate: 'Unknown export date',
    exportJson: 'Export JSON',
    importJson: 'Import JSON',
    importPreviewEyebrow: 'Import Preview',
    readyToReplace: 'Ready to replace',
    replaceLocalData: 'Replace Local Data',
    cancel: 'Cancel',
    backupSummaryLabels: {
      realProspects: 'Real Prospects',
      savedProspects: 'Saved Prospects',
      routeStops: 'Route Stops',
      notes: 'Notes',
      priorityEdits: 'Priority Edits',
      followUps: 'Follow-Ups',
    },
    importWarning:
      'Confirming this import will replace the current RepRoute data stored on this device.',
  },
  crmExport: {
    eyebrow: 'CRM Export',
    heading: 'CRM Export',
    description:
      'Keep everything local for now. RepRoute maps your fields into CRM-ready CSV headers so direct API integrations can plug into the same profiles later.',
    exportFormatLabel: 'Export Format',
    exportScopeLabel: 'Export Scope',
    previewEyebrow: 'Preview',
    rowsLabel: (count: number) => `${count} row${count === 1 ? '' : 's'}`,
    recordsLabel: (count: number) => `${count} record${count === 1 ? '' : 's'}`,
    futureIntegrationsLabel: (targets: string[]) =>
      `Future direct integrations planned: ${targets.join(', ')}`,
    downloadLabel: (label: string) => `Download ${label}`,
    successMessage: (count: number, label: string) =>
      `Exported ${count} record${count === 1 ? '' : 's'} as ${label}.`,
    formats: {
      generic: 'CSV for Any CRM',
      hubspot: 'HubSpot-Ready CSV',
      salesforce: 'Salesforce-Ready CSV',
      zoho: 'Zoho-Ready CSV',
      pipedrive: 'Pipedrive-Ready CSV',
    },
    futureTargets: {
      generic: 'Generic CSV importer',
      hubspot: 'HubSpot',
      salesforce: 'Salesforce',
      zoho: 'Zoho',
      pipedrive: 'Pipedrive',
    },
    previewFallback: '—',
    scopes: {
      saved: 'Saved Prospects Only',
      route: 'Today’s Route Only',
      followups: 'Follow-Ups Only',
      all: 'All RepRoute Data',
    },
  },
  errors: {
    apiErrorLabel: 'API Error',
    searchMissingFields: 'Enter both a keyword and city before running a live Google Places search.',
    searchMissingFieldsDetail: 'Google Places needs both fields to return real business results.',
    searchFailedDetail: 'Google Places search failed. Review the API response and try again.',
    connectGooglePlaces: 'Connect Google Places to search real businesses.',
    connectGooglePlacesDetail: 'Add a valid `VITE_GOOGLE_MAPS_API_KEY` to load live Places results.',
    mapApiKeyMissing: 'Google Maps API key missing',
    mapFailedToLoad: 'Map failed to load',
    loadingMap: 'Loading map...',
    noRatingYet: 'No rating yet',
    websiteUnavailable: 'Website unavailable',
    googlePlacesConnectionRunning: 'Testing Google Places with “equipment rental Austin TX”...',
    googlePlacesConnectionSucceeded: 'Google Places connection succeeded.',
    googlePlacesConnectionFailed: 'Google Places connection failed.',
    noCrmDataForScope: 'No Prospects are available for that CRM Export scope yet.',
    crmExportFailed: 'RepRoute could not generate that CRM Export CSV.',
    backupExportFailed: 'RepRoute could not export a backup file.',
    backupReadFailed: 'RepRoute could not read that backup file.',
    backupLoaded: 'Backup loaded. Review the preview before replacing local data.',
    backupExported: 'RepRoute data exported as a JSON backup.',
    backupImported: (fileName: string) =>
      `Imported ${fileName}. Existing local RepRoute data was replaced.`,
  },
  emptyStates: {
    noRealProspectsTitle: 'No Real Prospects Loaded Yet',
    noRealProspectsCopy: 'Connect Google Places to search real businesses.',
    noRouteTitle: 'Your Route is empty',
    noRouteCopy: 'Add Prospects from Search or Saved Prospects to build today’s Route.',
    noNearbyTitle: 'No Nearby Prospects Yet',
    noNearbyCopy:
      'Search more real businesses to surface nearby suggestions within 5 miles of your Route.',
    noSavedTitle: 'No Saved Prospects Yet',
    noSavedCopy: 'Save a Prospect to keep it ready for a future Route or Follow-Up.',
    noHotProspectsTitle: 'No Hot Prospects Yet',
    noHotProspectsCopy:
      'Use Search to qualify real businesses and mark the best opportunities as Hot.',
    noFollowUpsTitle: 'No Follow-Ups Scheduled',
    noFollowUpsCopy:
      'Use the Manage panel on any Prospect to schedule a Follow-Up and it will appear here.',
    noCrmDataTitle: 'No CRM Export Data For This Scope',
    noCrmDataCopy:
      'Search and save real Prospects, add them to a Route, or schedule Follow-Ups before exporting.',
    noSearchResultsTitle: 'No Real Businesses Found',
    noSearchResultsCopy: 'No real businesses found. Try a different keyword or location.',
    googlePlacesSearchFailedTitle: 'Google Places Search Failed',
    connectGooglePlacesTitle: 'Connect Google Places',
    noRouteLoadedTitle: 'No Route Loaded Yet',
    noRouteLoadedCopy:
      'Add Prospects from Search or Saved Prospects to build today’s Route.',
  },
} as const

export type UiText = typeof uiText
