export const uiText = {
  common: {
    more: 'More',
  },
  onboarding: {
    title: 'Get Started',
    description: 'Set up your workspace and start building a Prospect pipeline.',
    heroBadge: 'Live Route Planning',
    heroHeading: 'Build a sharper field day with businesses, Routes, and Follow-Ups that stick.',
    heroDescription:
      'RepRoute remembers your Prospects, Saved Prospects, Route stops, notes, priorities, and Follow-Up dates between visits.',
    metrics: {
      realProspectsLoaded: 'Prospects Loaded',
      savedProspects: 'Saved Prospects',
      routeStops: 'Route Stops',
      followUpsDue: 'Follow-Ups Due',
    },
    actions: {
      findProspects: 'Find Prospects',
      viewRoute: 'View Route',
    },
    startHereEyebrow: 'Start Here',
    searchStatusEyebrow: 'Live Search Status',
    realProspectsDetail: 'Live Search businesses currently stored on this device.',
    catalogSummary:
      'Saved Prospects, Route stops, and Follow-Ups all come from Live Search activity.',
    upcomingFollowUpsDetail: (count: number) => `${count} scheduled in the next seven days`,
    storedProspectsSummary: (count: number) => `${count} businesses stored locally`,
    hotTargetsEyebrow: 'Best Nearby Opportunities',
    hotTargetsHeading: 'Hot Targets',
    nextFollowUp: 'Next Follow-Up',
    hotTargetsEmptyAction: 'Open Search',
  },
  navigation: {
    appName: 'RepRoute',
    tagline: 'Field Sales Route Planner',
    liveBadge: 'RepRoute',
    primaryNavAriaLabel: 'Primary',
    themeToggleAriaLabel: 'Toggle color theme',
    items: {
      dashboard: 'Home',
      map: 'Route',
      search: 'Search',
      saved: 'Saved',
      followUps: 'Follow-Ups',
      settings: 'Settings',
    },
    screenMeta: {
      dashboard: {
        title: 'Territory Command',
        subtitle:
          'Search businesses with Prospect Search and keep your Route activity saved locally.',
      },
      map: {
        title: 'Route',
        subtitle: 'Optimize, navigate, and work each stop.',
      },
      search: {
        title: 'Search',
        subtitle: 'Find businesses and add them to your route.',
      },
      saved: {
        title: 'Saved',
        subtitle: 'Prospects you saved for later.',
      },
      'follow-ups': {
        title: 'Follow-Ups',
        subtitle: 'Pending and completed follow-ups.',
      },
      settings: {
        title: 'Settings',
        subtitle: 'Backup, export, notifications, and location.',
      },
    },
    accountMenu: {
      ariaLabel: 'Open profile menu',
      settings: 'Settings',
      exportCrm: 'Export CRM Data',
      backup: 'Backup Data',
      signIn: 'Sign In',
      signInPlaceholder:
        'Sign in is coming soon. This account menu is ready for future authentication.',
      workspaceTitle: 'RepRoute Workspace',
      workspaceDescription:
        'No account is connected yet. This profile area is ready for future sign-in support.',
    },
    travelMode: {
      label: 'Travel mode',
      driving: 'Driving',
      walking: 'Walking',
    },
  },
  search: {
    eyebrow: 'Territory Search',
    heading: 'Find Prospects',
    prominentTitle: 'Find prospects',
    prominentDescription:
      'Run a Live Search by target industry and radius, then save qualified Prospects or add them to a Route.',
    companyNameLabel: 'Company name',
    companyNamePlaceholder: 'Search for a specific company',
    companyNameClear: 'Clear company name',
    marketLabel: 'City or market',
    marketPlaceholder: 'Optional city or market',
    marketHelp: 'Leave blank to search near your current location.',
    locationPanel: {
      heading: 'Location access',
      helper: 'Use your current location to search businesses within your selected mileage radius.',
      statusOn: 'Location on',
      statusOff: 'Location off',
      statusNeeded: 'Permission needed',
      statusUnavailable: 'Location unavailable',
      turnOn: 'Turn On Location',
      blocked:
        'Location access is blocked. Enable it in Safari or browser settings, or enter a market manually.',
    },
    radiusLabel: 'Mileage radius',
    radiusOptions: [5, 10, 15, 25, 50] as const,
    radiusOptionLabels: {
      currentLocation: 'Use my current location',
      custom: 'Custom radius',
    },
    customRadiusLabel: 'Custom mileage radius',
    industriesLabel: 'Target industries (optional)',
    industriesPlaceholder: 'Select industries',
    industriesSearchPlaceholder: 'Search industries',
    industriesSelectAll: 'Select All',
    industriesClearAll: 'Clear All',
    industriesSelectAllInCategory: 'Select All in Category',
    industriesClearCategory: 'Clear Category',
    industriesEmpty: 'No industries match your search.',
    industriesSectionSelected: (count: number) =>
      count === 0 ? 'No selections' : count === 1 ? '1 selected' : `${count} selected`,
    industriesSelected: (count: number) =>
      count === 0
        ? 'No selections'
        : count === 1
          ? '1 industry selected'
          : `${count} industries selected`,
    industryGroups: [
      {
        label: 'Construction & Trades',
        options: [
          'General Contractors',
          'HVAC Contractors',
          'Plumbing Contractors',
          'Electrical Contractors',
          'Roofing Contractors',
          'Concrete Contractors',
          'Excavation Contractors',
          'Framing Contractors',
          'Fire Protection',
          'Glass & Glazing',
          'Flooring Contractors',
          'Painting Contractors',
          'Landscaping',
          'Pool Contractors',
        ] as const,
      },
      {
        label: 'Industrial & Energy',
        options: [
          'Oil & Gas',
          'Midstream',
          'Upstream',
          'Downstream',
          'Refineries',
          'Petrochemical',
          'Industrial Supply',
          'Hydraulic Repair',
          'Hose & Fittings',
          'Welding & Fabrication',
          'Automation & Controls',
          'Bearings & Power Transmission',
          'Pumps & Process Equipment',
          'Compressors',
          'Valve & Instrumentation',
          'Data Centers',
          'Power Generation',
          'Renewable Energy',
          'Water Treatment',
          'Wastewater',
        ] as const,
      },
      {
        label: 'Equipment & Transportation',
        options: [
          'Equipment Rental',
          'Heavy Equipment Dealers',
          'Fleet Services',
          'Trucking & Logistics',
          'Warehousing',
          'Freight Brokers',
          'Trailer Repair',
          'Automotive Repair',
          'Tire Shops',
          'Forklift Dealers',
          'Crane Services',
        ] as const,
      },
      {
        label: 'Commercial & Facilities',
        options: [
          'Property Management',
          'Commercial Real Estate',
          'Facilities Maintenance',
          'Janitorial Services',
          'Security Services',
          'Building Maintenance',
          'Municipal & Government',
          'Schools & Universities',
          'Hospitals & Clinics',
          'Hotels & Hospitality',
          'Restaurants & Food Service',
        ] as const,
      },
      {
        label: 'Agriculture & Outdoor',
        options: [
          'Agriculture',
          'Irrigation',
          'Feed & Seed',
          'Ranch Supply',
          'Forestry',
          'Outdoor Power Equipment',
        ] as const,
      },
      {
        label: 'Manufacturing',
        options: [
          'CNC Machining',
          'Metal Fabrication',
          'Plastic Manufacturing',
          'Packaging',
          'Food Manufacturing',
          'Chemical Manufacturing',
          'Assembly Plants',
        ] as const,
      },
      {
        label: 'Technology & Office',
        options: [
          'IT Services',
          'Telecom',
          'Office Supply',
          'Print & Sign Shops',
          'Marketing Agencies',
        ] as const,
      },
    ] as const,
    searchButton: 'Search Businesses',
    searchingButton: 'Searching Businesses...',
    suggestedSearchesLabel: 'Suggested Searches',
    suggestedKeywords: [
      'equipment rental',
      'pipeline operators',
      'natural gas companies',
      'oilfield services',
      'industrial supply',
      'HVAC contractors',
      'electrical contractors',
      'plumbing contractors',
      'construction companies',
    ],
    statusHeading: 'Live Search Status',
    catalogHeading: 'Business Catalog',
    resultsEyebrow: 'Live Results',
    resultsHeading: 'Search Results',
    testButton: 'Test',
    openSettings: 'Open settings',
    selectedFiltersLabel: 'Selected Filters',
    filters: {
      radius: (miles: number) => `${miles} miles`,
      industries: (industries: string[]) => industries.join(', '),
      market: (market: string) => `Market: ${market}`,
      companyName: (name: string) => `Company: ${name}`,
      currentLocation: 'Current location',
    },
    location: {
      locating: 'Finding your current location...',
      ready: 'Using your current location as the default search center.',
      denied: 'Enable location access or enter a market manually.',
      unsupported: 'Location is unavailable in this browser. Enter a market manually.',
      marketOverride: (market: string) => `Using ${market} as the search center.`,
    },
    statusMessages: {
      liveResults: (count: number, summary: string) =>
        `Live Search returned ${count} business result${count === 1 ? '' : 's'} for ${summary}.`,
      noLiveResults: (summary: string) => `No business results found for ${summary}.`,
      noLiveResultsWithinRadius:
        'No businesses found within this radius. Try increasing the mileage radius.',
    },
    radiusHardFilterSummary: (miles: number, centerLabel: string) =>
      `Showing businesses within ${miles} miles of ${centerLabel}.`,
    summary: {
      results: (count: number) => `${count} live result${count === 1 ? '' : 's'}`,
      error: 'Search error',
      resultsReturned: (count: number) => `${count} result${count === 1 ? '' : 's'} returned.`,
    },
    card: {
      badge: 'Live Search',
      searchResult: 'Search Result',
      save: 'Save Prospect',
      saved: 'Saved to Prospects',
      removeSaved: 'Remove Saved Prospect',
      removeProspect: 'Remove Prospect',
      addToRoute: 'Add to Route',
      inRoute: 'Remove from Route',
      removeRoute: 'Remove from Route',
      openSaved: 'Open Saved',
      openInMaps: 'Open in Maps',
      navigateDrive: 'Navigate Drive',
      navigateWalk: 'Navigate Walk',
    },
    prospectCard: {
      removeFromSavedAria: 'Remove from Saved Prospects',
      saveProspectAria: 'Save Prospect',
      followUpPrefix: 'Follow-Up',
      notes: 'Notes',
      nextTouch: 'Next Touch',
      removeRoute: 'Remove from Route',
      manage: 'Manage',
      hide: 'Hide',
      priority: 'Priority',
      followUpDate: 'Follow-Up Date',
      clear: 'Clear',
      prospectNotes: 'Prospect Notes',
      editorHint: 'Edits save instantly to local storage on this device.',
    },
  },
  foodNearby: {
    eyebrow: 'Quick Nearby',
    heading: (name: string) => `Food Near ${name}`,
    backToProspect: 'Back to Prospect',
    closeFoodNearby: 'Close Food Nearby',
    closeAriaLabel: 'Close Food Nearby',
    description:
      'Find restaurants, coffee, or catering nearby before your next visit. Results are filtered to your selected distance.',
    radiusLabel: 'Distance filter',
    radiusOption: (miles: number) => `Within ${miles} mi`,
    quickFiltersLabel: 'Quick filters',
    quickFilterAll: 'All',
    loading: 'Searching nearby food options…',
    empty: 'No food options found nearby.',
    resultBadge: 'Nearby',
    distanceAway: (miles: string) => `${miles} from stop`,
    navigate: 'Navigate',
    saveAsFoodStop: 'Save as Food Stop',
    savedAsFoodStop: 'Saved as Food Stop',
    close: 'Close',
    findFoodNearby: 'Find Food Nearby',
    foodStopLabel: 'Food Stop',
    addedFoodStopToast: 'Added Food Stop to Today’s Route.',
  },
  saved: {
    eyebrow: 'Saved Pipeline',
    heading: 'Saved Prospects',
    countLabel: (count: number) => `${count} saved`,
    savedMessage: 'Saved to Prospects',
    summaryPrimaryTitle: 'Keep the bench warm',
    summaryPrimaryDescription:
      'Saved Prospects stay available even when they are not on today’s Route.',
    summarySecondaryTitle: 'Notes stay attached',
    summarySecondaryDescription:
      'Every note, priority, and Follow-Up date is stored locally for future visits.',
    notesPreview: 'Notes Preview',
    notesPreviewEmpty: 'No notes added yet for this Prospect.',
    followUpStatus: 'Follow-Up Status',
    routeStatus: 'Route Status',
    routeStatusInRoute: 'In Today’s Route',
    routeStatusNotInRoute: 'Not in Route',
    lastVisited: 'Last Visited',
    lastVisitedEmpty: 'Not visited yet',
    edit: 'Edit',
    remove: 'Remove',
    openSaved: 'Open Saved',
    emptyAction: 'Browse Prospects',
  },
  routes: {
    suggestedKeywordCta: 'Find prospects',
    optimization: {
      button: 'Optimize Route',
      optimizing: 'Optimizing route…',
      optimized: 'Route optimized.',
      error: 'Route could not be optimized. Check that every stop has an address or location.',
      locationOffMessage: 'Location access is off. Enter a starting location to optimize or navigate.',
      startingLocationLabel: 'Starting location',
      startingLocationPlaceholder: 'Use current location or enter a starting address',
      useCurrentLocation: 'Use My Current Location',
      largeRouteBatch: (count: number) =>
        `Large route detected. Optimizing first ${count} stops.`,
      noStops: 'Add route stops before navigating.',
      missingCoordinates: 'One or more stops are missing coordinates. Try removing and re-adding them.',
      invalidStop: (name: string) => `Missing address or location for: ${name}`,
      startPromptHeading: 'Choose a starting point',
      startPromptDescription:
        'Enter a starting address or landmark. RepRoute uses this as the route origin when current location is unavailable.',
      startPromptLabel: 'Starting point',
      startPromptPlaceholder: 'Enter an address or landmark',
      startPromptConfirm: 'Optimize Route',
      startPromptCancel: 'Cancel',
      totalDistance: (miles: string) => `Total distance: ${miles} mi`,
      totalDriveTime: (time: string) => `Total drive time: ${time}`,
    },
    calculation: {
      eyebrow: 'Route Builder',
      heading: 'Calculate Route',
      description:
        'Finalize your selected stops and jump straight into Today’s Route without hunting for the Route tab.',
      button: 'Calculate Route',
      summaryHeading: 'Route Summary',
      emptyState: 'Add prospects to build a route.',
      singleStopHint: 'Add more stops to optimize a multi-stop route.',
      readyToOptimize: 'Ready to optimize your route.',
      multiStopHint: 'Route ready in RepRoute. Review your stops, then start route guidance here.',
      stopCount: (count: number) => `${count} stop${count === 1 ? '' : 's'}`,
      estimatedDrive: (time: string) => `Est. drive time: ${time}`,
      travelMode: (mode: string) => `Travel mode: ${mode}`,
      filters: (summary: string) => `Filters: ${summary}`,
    },
    routeSnapshotEyebrow: 'Today’s Route',
    routeSnapshotHeading: 'Route Snapshot',
    openRoute: 'Open Route',
    routeMapEyebrow: 'Live Route Map',
    routeMapHeading: 'Route Map',
    routeMapDescription:
      'Search results, Saved Prospects, and Route stops stay visible on the map while you work the day.',
    currentLocation: 'Your current location',
    todayListSummary: (count: number) => `${count} stops in today’s list`,
    navigateEntireRoute: 'Open in Maps',
    clearRoute: 'Clear Route',
    inAppNavigation: {
      eyebrow: 'Route Navigation',
      heading: 'Following Today’s Route',
      back: 'Back to Route Overview',
      addToRouteToNavigate: 'Add this prospect to Today’s Route to navigate inside RepRoute.',
      mapsPopupBlocked: 'Allow pop-ups in your browser to open directions in your maps app.',
      overviewEyebrow: 'Route guidance',
      overviewHeading: 'Today’s Route overview',
      currentStopLabel: 'Current stop',
      nextStopLabel: 'Next stop',
      etaLabel: 'ETA',
      distanceLabel: 'Distance',
      startRoute: 'Start Route',
      openInMaps: 'Open in Maps',
      openInMapsHint: 'Open the optimized route in your preferred maps app.',
      loadingRoute: 'Loading route line…',
      needOrigin: 'Add a starting location or enable location access to start route navigation.',
      routeLineError: 'Could not draw the route line. Stops and visit actions are still available.',
      partialRouteLine: 'Route line shows the first segment of a large route. Navigation and stops are unchanged.',
      mapNotReady: 'Map is still loading. Route line will appear when the map is ready.',
      upNext: 'Up next',
      stopsEyebrow: 'Stop sequence',
      stopsHeading: 'Route stops',
      nextStop: (businessName: string) => `Next: ${businessName}`,
      stopOrder: (current: number, total: number) => `Stop ${current} of ${total}`,
      completedCount: (count: number) => `${count} completed`,
      remainingCount: (count: number) => `${count} remaining`,
      percentComplete: (percent: number) => `${percent}% complete`,
      activeStop: 'Active stop',
      arrived: 'Arrived',
      markArrived: 'Mark Arrived',
      markCompleted: 'Mark Completed',
      addNotes: 'Add Notes',
      distanceToStop: (distance: string) => `${distance} to stop`,
      timeToStop: (duration: string) => `${duration} drive`,
      atStart: 'At route start',
      noTurnByTurn: 'Turn-by-turn voice guidance is not included in this version.',
    },
    routeRender: {
      diagnosticsHeading: 'Route Diagnostics',
      stopCount: (count: number) => `${count} stops`,
      optimizedCount: (count: number) => `${count} optimized`,
      skippedCount: (count: number) => `${count} sequential`,
      apiStatus: (status: string) => `API: ${status}`,
      validStops: (count: number) => `${count} valid stops`,
      invalidRemoved: (count: number) => `${count} invalid stops removed`,
      routeStatus: 'Route status',
      directionsStatus: 'Directions API status',
      rendererStatus: 'Renderer status',
      mapReady: 'Map ready',
      mapLoading: 'Map loading',
      usedFallback: 'Used sequential fallback route',
      autoRemoved: 'Auto-removed invalid stops from route',
    },
    businessCard: {
      heading: 'Business Card',
      description: 'Scan or upload a business card photo for this stop. Contact details save with the prospect.',
      scanCard: 'Scan Business Card',
      replaceCard: 'Replace Card',
      viewCard: 'View Card',
      removeCard: 'Remove Card',
      uploadFallback: 'Upload Image',
      extractContactInfo: 'Extract contact info',
      previewAlt: (prospectId: string) => `Business card for prospect ${prospectId}`,
      closeViewer: 'Close',
      captureFailed: 'Could not save the business card image.',
      removed: 'Business card removed.',
      attachPromptHeading: 'Attach this card to which stop?',
      attachPromptDescription: 'Choose the route stop that should receive this business card.',
      attachPromptCancel: 'Cancel',
      routeActionBarLabel: 'Route tools',
    },
    invalidStops: {
      eyebrow: 'Route Check',
      heading: 'Invalid Stops',
      description:
        'Some stops are missing info needed for route calculation. Remove or update them, then recalculate.',
      removeAndRecalculate: 'Remove Invalid Stops and Recalculate',
      noValidStops: 'No valid stops available for route calculation.',
      missingAddress: 'Missing address',
      missingCoordinates: 'Missing coordinates',
      missingPlaceId: 'Missing place ID',
      removeStop: 'Remove Stop',
      editAddress: 'Edit Address',
      addressLabel: 'Address',
      addressPlaceholder: 'Enter a full address',
      saveAddress: 'Save Address',
      cancel: 'Cancel',
    },
    mapSummary: {
      searchResults: (count: number) => `${count} search results`,
      savedProspects: (count: number) => `${count} Saved Prospects`,
      routeStops: (count: number) => `${count} Route stops`,
      visiblePins: (count: number) => `${count} visible pins`,
      routeMiles: (miles: string) => `${miles} total Route miles`,
      nearbySuggestions: (count: number) => `${count} nearby suggestions`,
    },
    stats: {
      routeStopsLabel: 'Today’s Route',
      routeStopsDetail: (miles: string) => `${miles} currently loaded into the Route`,
      completedStops: 'Completed Stops',
      completedStopsDetail: (remaining: number) => `${remaining} remaining on today’s Route`,
      estimatedDriveTime: 'Estimated Drive Time',
      estimatedDriveTimeDetail: (miles: string) => `${miles} currently planned`,
      completion: 'Completion',
      completionDetail: 'Progress across the active Route',
      nearbyProspects: 'Nearby Prospects',
      nearbyProspectsDetail: 'Within 5 miles of the current Route',
    },
    fieldWorkflowEyebrow: 'Field Workflow',
    fieldWorkflowHeading: 'Today’s Route',
    routeReady: 'Route ready',
    nextStop: (businessName: string) => `Next: ${businessName}`,
    currentStop: {
      eyebrow: 'Current Stop',
      heading: 'Current Stop',
      label: 'Current Stop',
      onLocation: 'You’re on location',
      enRoute: 'En route',
      tracking: 'Tracking your current location for arrival check-ins.',
      waiting: 'Waiting for a route location fix to start arrival detection.',
      locationDenied: 'Allow location access to trigger on-location prospect check-ins.',
      locationUnsupported: 'Arrival detection is unavailable in this browser.',
      locationError: 'RepRoute could not update your route location right now.',
      onLocationMessage: (businessName: string, distance: string) =>
        `You’re on location at ${businessName}. RepRoute detected you ${distance} from this stop.`,
      nearestMessage: (businessName: string, distance: string) =>
        `${businessName} is the closest stop at ${distance}.`,
      distanceAway: (distance: string) => `Distance away: ${distance}`,
      quickActions: {
        markCompleted: 'Mark Completed',
        markIncomplete: 'Mark Incomplete',
        saveProspect: 'Save Prospect',
        openSaved: 'Open Saved',
        editContactInfo: 'Edit Contact Info',
        addVisitNotes: 'Add Visit Notes',
        setFollowUp: 'Set Follow-Up',
        changePriority: 'Change Priority',
        addOutcomeTag: 'Add Outcome Tag',
      },
      contactFields: {
        contactName: 'Contact Name',
        contactTitle: 'Contact Title',
        phone: 'Phone',
        email: 'Email',
        website: 'Website',
        notes: 'Notes',
      },
    },
    currentFocusTitle: 'Current Focus',
    routeStopInfo: (order?: number) => `Route stop ${order ?? ''}`.trim(),
    stopLabel: (index: number) => `Stop ${index + 1}`,
    completed: 'Completed',
    markStopCompleteAria: 'Mark stop complete',
    markStopIncompleteAria: 'Mark stop incomplete',
    reorderStopAria: 'Reorder stop',
    actions: {
      callBusiness: 'Call Business',
      openWebsite: 'Open Website',
      navigateDrive: 'Navigate Drive',
      navigateWalk: 'Navigate Walk',
      remove: 'Remove',
      removeProspect: 'Remove Prospect',
      saveProspect: 'Save Prospect',
      openSaved: 'Open Saved',
      addNearbyProspect: 'Add Nearby Prospect',
      addToRoute: 'Add to Route',
      addedToRouteToast: 'Added to Today’s Route',
    },
    removal: {
      heading: 'Remove Prospect',
      description:
        'Choose how to remove this Prospect. Notes, Follow-Ups, CRM export data, and visit history stay available on this device.',
      removeFromRoute: 'Remove from Route',
      removeFromSaved: 'Remove from Saved Prospects',
      cancel: 'Cancel',
    },
    visitOutcomeLabel: 'Visit Outcome',
    quickNoteLabel: 'Quick Note After Visit',
    quickNotePlaceholder: 'Capture what happened at this stop...',
    nearbyEyebrow: 'Nearby Coverage',
    nearbyHeading: 'Nearby Prospects',
    withinFiveMiles: 'Within 5 Miles',
    nearbyDistanceLabel: (distance: number) => `${distance.toFixed(1)} mi from Route`,
    outcomeTags: [
      'No Answer',
      'Decision Maker Met',
      'Follow-Up Needed',
      'Quote Opportunity',
      'Not Interested',
      'Bad Address',
      'Existing Customer',
    ] as const,
  },
  followUps: {
    noDate: 'No Follow-Up set',
    savedToast: 'Follow-Up Saved',
    stats: {
      scheduled: 'Scheduled Follow-Ups',
      scheduledDetail: 'Every Follow-Up currently tracked on this device',
      dueNow: 'Due Now',
      dueNowDetail: 'Prospects that should be touched today or earlier',
      thisWeek: 'This Week',
      thisWeekDetail: 'Follow-Ups due within the next seven days',
    },
    sections: {
      pending: 'Pending',
      overdue: 'Overdue',
      today: 'Today',
      upcoming: 'Upcoming',
      completed: 'Completed',
    },
    timeLabel: 'Follow-Up Time',
    notesLabel: 'Follow-Up Notes',
    notesEmpty: 'No notes added yet.',
    priorityLabel: (priority: string) => `Priority: ${priority}`,
    routeStatusOnRoute: 'On Today’s Route',
    routeStatusSaved: 'Saved Prospect',
    routeStatusNotInRoute: 'Not on Route',
    completedLabel: 'Completed',
    markComplete: 'Mark Complete',
    edit: 'Edit',
    rescheduleTomorrow: 'Reschedule to Tomorrow',
    navigate: 'Navigate',
    addNotes: 'Add Notes',
    remove: 'Remove',
    saveChanges: 'Save Follow-Up',
    saveFollowUp: 'Save Follow-Up',
    openProspect: 'Open Prospect',
    savedStatus: 'Saved Prospect',
    unsavedStatus: 'Unsaved Prospect',
    nextFollowUp: 'Next Follow-Up',
    statuses: {
      dueNow: 'Due Now',
      tomorrow: 'Tomorrow',
      thisWeek: 'This Week',
      later: 'Later',
    },
  },
  settings: {
    appearanceTitle: 'Appearance',
    appearanceDescription: 'Switch between dark and light workspace themes.',
    darkMode: 'Dark mode',
    lightMode: 'Light mode',
    arrivalDetectionTitle: 'Arrival Detection Radius',
    arrivalDetectionDescription:
      'Choose how close you need to be before RepRoute marks a Route stop as on location.',
    arrivalDetectionLabel: 'Arrival Detection Radius',
    arrivalDetectionOption: (feet: number) =>
      feet >= 1320 ? '0.25 miles' : `${feet.toLocaleString()} feet`,
    googlePlacesEyebrow: 'Live Search',
    googlePlacesHeading: 'Search Connection',
    apiKeyDetected: 'API key detected',
    apiKeyMissing: 'API key missing',
    googlePlacesDescription:
      'Run a sample market search for “equipment rental Austin TX” to confirm live business results are loading.',
    testConnectionButton: 'Test Live Search',
    resultsReturned: (count: number) => `Results returned: ${count}`,
    errorDetails: (details: string) => `Error details: ${details}`,
    notifications: {
      eyebrow: 'Notifications',
      heading: 'Reminder Notifications',
      description:
        'Enable local browser reminders for Follow-Ups, today’s Route, and overdue Prospects. These alerts run on this device with no backend required.',
      localOnlyNote:
        'Notifications are local only. Keep RepRoute open in the browser or installed as a PWA for reminders to trigger without a server.',
      permissionPromptTitle: 'Allow Browser Notifications',
      permissionPromptDescription:
        'RepRoute needs notification permission before it can send local reminder alerts on mobile or desktop.',
      requestPermission: 'Enable Notifications',
      permissionStatusLabel: 'Permission Status',
      permissionStatuses: {
        granted: 'Allowed',
        denied: 'Blocked',
        default: 'Ask First',
        unsupported: 'Unsupported',
      },
      toggles: {
        enable: 'Enable Notifications',
        enableDescription: 'Allow RepRoute to send local reminder notifications on this device.',
        followUps: 'Follow-Up Alerts',
        followUpsDescription: 'Send a reminder when Prospects are due for a Follow-Up today.',
        route: 'Daily Route Reminder',
        routeDescription: 'Send a reminder for today’s Route so the day starts with the next stop in view.',
        overdue: 'Overdue Prospect Alerts',
        overdueDescription: 'Send a reminder when Follow-Ups have slipped past their scheduled date.',
      },
      timeLabel: 'Reminder Time',
      routeTimeLabel: 'Daily Route Reminder Time',
      followUpTimeLabel: 'Follow-Up Reminder Time',
      overdueTimeLabel: 'Overdue Prospect Alert Time',
      states: {
        on: 'On',
        off: 'Off',
      },
      messages: {
        permissionGranted: 'Browser notifications are enabled for this device.',
        permissionDenied:
          'Notification permission is blocked. Update your browser settings to re-enable alerts.',
        permissionUnsupported:
          'This browser does not support notifications, so local reminder alerts are unavailable.',
        notificationsDisabled: 'Local reminder notifications are turned off.',
        reminderDelivered: 'Reminder notifications are active and will fire at the times you selected.',
      },
      reminders: {
        followUpTitle: (count: number) =>
          `${count} Follow-Up${count === 1 ? '' : 's'} Due Today`,
        followUpBody: (names: string[]) =>
          names.length > 0
            ? `${names.join(', ')} ${names.length === 1 ? 'needs' : 'need'} attention today.`
            : 'You have Follow-Ups due today in RepRoute.',
        routeTitle: (count: number) => `Today’s Route Has ${count} Stop${count === 1 ? '' : 's'}`,
        routeBody: (nextStop: string | null) =>
          nextStop
            ? `Next stop: ${nextStop}. Open RepRoute to review the Route.`
            : 'Open RepRoute to review your Route for today.',
        overdueTitle: (count: number) =>
          `${count} Overdue Prospect${count === 1 ? '' : 's'} Need Attention`,
        overdueBody: (names: string[]) =>
          names.length > 0
            ? `${names.join(', ')} ${names.length === 1 ? 'is' : 'are'} overdue for Follow-Up.`
            : 'You have overdue Prospects waiting for Follow-Up.',
      },
    },
    storageEyebrow: 'Storage Status',
    storageHeading: 'Local-First Data',
    storageLocalTitle: 'Saved locally',
    storageLocalDescription:
      'Prospects, Saved Prospects, Route stops, notes, priorities, and dates stay on this device.',
    storageLiveTitle: 'Live search only',
    storageLiveDescription:
      'RepRoute relies on Live Search for business discovery and does not use fallback business data.',
    backupEyebrow: 'Data Backup',
    backupHeading: 'Data Backup',
    backupDescription:
      'Export a JSON snapshot of your local RepRoute data, or preview a backup before replacing current data on this device.',
    unknownExportDate: 'Unknown export date',
    exportJson: 'Export JSON',
    importJson: 'Import JSON',
    importPreviewEyebrow: 'Import Preview',
    readyToReplace: 'Ready to replace',
    replaceLocalData: 'Replace Local Data',
    cancel: 'Cancel',
    backupSummaryLabels: {
      realProspects: 'Prospects',
      savedProspects: 'Saved Prospects',
      routeStops: 'Route Stops',
      notes: 'Notes',
      priorityEdits: 'Priority Edits',
      followUps: 'Follow-Ups',
    },
    importWarning:
      'Confirming this import will replace the current RepRoute data stored on this device.',
  },
  crmExport: {
    eyebrow: 'CRM Export',
    heading: 'CRM Export',
    description:
      'Keep everything local for now. RepRoute maps your fields into CRM-ready CSV headers so direct API integrations can plug into the same profiles later.',
    exportFormatLabel: 'Export Format',
    exportScopeLabel: 'Export Scope',
    previewEyebrow: 'Preview',
    rowsLabel: (count: number) => `${count} row${count === 1 ? '' : 's'}`,
    recordsLabel: (count: number) => `${count} record${count === 1 ? '' : 's'}`,
    futureIntegrationsLabel: (targets: string[]) =>
      `Future direct integrations planned: ${targets.join(', ')}`,
    downloadLabel: (label: string) => `Download ${label}`,
    successMessage: (count: number, label: string) =>
      `Exported ${count} record${count === 1 ? '' : 's'} as ${label}.`,
    formats: {
      generic: 'CSV for Any CRM',
      hubspot: 'HubSpot-Ready CSV',
      salesforce: 'Salesforce-Ready CSV',
      zoho: 'Zoho-Ready CSV',
      pipedrive: 'Pipedrive-Ready CSV',
      wpcrm: 'WPCRM-ready CSV',
    },
    futureTargets: {
      generic: 'Generic CSV importer',
      hubspot: 'HubSpot',
      salesforce: 'Salesforce',
      zoho: 'Zoho',
      pipedrive: 'Pipedrive',
      wpcrm: 'WPCRM (direct API sync planned)',
    },
    previewFallback: '—',
    scopes: {
      saved: 'Saved Prospects Only',
      route: 'Today’s Route Only',
      followups: 'Follow-Ups Only',
      all: 'All RepRoute Data',
    },
  },
  errors: {
    apiErrorLabel: 'API Error',
    searchMissingFields: 'Enter a company name or select at least one target industry.',
    searchMissingFieldsDetail:
      'Live Search needs a company name or at least one target industry to return business results.',
    searchFailedDetail: 'Live Search failed. Review the response and try again.',
    connectGooglePlaces: 'Enable Live Search to find businesses.',
    connectGooglePlacesDetail: 'Add a valid search API key to load live business results.',
    locationRequired: 'Enable location access or enter a market manually.',
    mapApiKeyMissing: 'Map key missing',
    mapFailedToLoad: 'Map failed to load',
    loadingMap: 'Loading map...',
    noRatingYet: 'No rating yet',
    websiteUnavailable: 'Website unavailable',
    googlePlacesConnectionRunning: 'Testing Live Search with “equipment rental Austin TX”...',
    googlePlacesConnectionSucceeded: 'Live Search connection succeeded.',
    googlePlacesConnectionFailed: 'Live Search connection failed.',
    noCrmDataForScope: 'No Prospects are available for that CRM Export scope yet.',
    crmExportFailed: 'RepRoute could not generate that CRM Export CSV.',
    backupExportFailed: 'RepRoute could not export a backup file.',
    backupReadFailed: 'RepRoute could not read that backup file.',
    backupLoaded: 'Backup loaded. Review the preview before replacing local data.',
    backupExported: 'RepRoute data exported as a JSON backup.',
    backupImported: (fileName: string) =>
      `Imported ${fileName}. Existing local RepRoute data was replaced.`,
  },
  emptyStates: {
    noRealProspectsTitle: 'No Prospects Loaded Yet',
    noRealProspectsCopy: 'Enable Live Search to find businesses.',
    noRouteTitle: 'No prospects currently in your route.',
    noRouteCopy: 'Add Prospects from Search or Saved Prospects to build today’s Route.',
    noNearbyTitle: 'No Nearby Prospects Yet',
    noNearbyCopy:
      'Search more businesses to surface nearby suggestions within 5 miles of your Route.',
    noSavedTitle: 'No Saved Prospects Yet',
    noSavedCopy: 'Save a Prospect to keep it ready for a future Route or Follow-Up.',
    noHotProspectsTitle: 'No Hot Prospects Yet',
    noHotProspectsCopy:
      'Use Search to qualify businesses and mark the best opportunities as Hot.',
    noFollowUpsTitle: 'No Follow-Ups Scheduled',
    noFollowUpsCopy:
      'Use the Manage panel on any Prospect to schedule a Follow-Up and it will appear here.',
    noCrmDataTitle: 'No CRM Export Data For This Scope',
    noCrmDataCopy:
      'Search and save Prospects, add them to a Route, or schedule Follow-Ups before exporting.',
    noSearchResultsTitle: 'No Businesses Found',
    noSearchResultsCopy: 'No businesses found. Try a different keyword or location.',
    googlePlacesSearchFailedTitle: 'Live Search Failed',
    connectGooglePlacesTitle: 'Enable Live Search',
    noRouteLoadedTitle: 'No prospects currently in your route.',
    noRouteLoadedCopy:
      'Add Prospects from Search or Saved Prospects to build today’s Route.',
  },
} as const

export type UiText = typeof uiText
