export const uiText = {
  onboarding: {
    title: 'Get Started',
    description: 'Set up your workspace and start building a Prospect pipeline.',
    heroBadge: 'Live Route Planning',
    heroHeading: 'Build a sharper field day with businesses, Routes, and Follow-Ups that stick.',
    heroDescription:
      'RepRoute remembers your Prospects, Saved Prospects, Route stops, notes, priorities, and Follow-Up dates between visits.',
    metrics: {
      realProspectsLoaded: 'Prospects Loaded',
      savedProspects: 'Saved Prospects',
      routeStops: 'Route Stops',
      followUpsDue: 'Follow-Ups Due',
    },
    actions: {
      findProspects: 'Find Prospects',
      viewRoute: 'View Route',
    },
    startHereEyebrow: 'Start Here',
    searchStatusEyebrow: 'Live Search Status',
    realProspectsDetail: 'Live Search businesses currently stored on this device.',
    catalogSummary:
      'Saved Prospects, Route stops, and Follow-Ups all come from Live Search activity.',
    upcomingFollowUpsDetail: (count: number) => `${count} scheduled in the next seven days`,
    storedProspectsSummary: (count: number) => `${count} businesses stored locally`,
    hotTargetsEyebrow: 'Best Nearby Opportunities',
    hotTargetsHeading: 'Hot Targets',
    nextFollowUp: 'Next Follow-Up',
    hotTargetsEmptyAction: 'Open Search',
  },
  navigation: {
    appName: 'RepRoute',
    tagline: 'Field Sales Route Planner',
    liveBadge: 'Live Search',
    primaryNavAriaLabel: 'Primary',
    themeToggleAriaLabel: 'Toggle color theme',
    items: {
      dashboard: 'Home',
      map: 'Route',
      search: 'Search',
      saved: 'Saved',
      followUps: 'Follow-Ups',
      settings: 'Settings',
    },
    screenMeta: {
      dashboard: {
        title: 'Territory Command',
        subtitle:
          'Search businesses with Prospect Search and keep your Route activity saved locally.',
      },
      map: {
        title: 'Today’s Route',
        subtitle:
          'Review your stops, navigate the day, and work through Route activity from one screen.',
      },
      search: {
        title: 'Prospect Search',
        subtitle:
          'Run a live Market Search by keyword and market, then save the best Prospects or add them to a Route.',
      },
      saved: {
        title: 'Saved Prospects',
        subtitle:
          'Keep high-fit Prospects ready for future Route days, follow-up work, and CRM export.',
      },
      'follow-ups': {
        title: 'Follow-Ups',
        subtitle: 'Track every scheduled Follow-Up in one mobile-friendly workspace.',
      },
      settings: {
        title: 'Settings',
        subtitle:
          'Manage notifications, Live Search, CRM Export, backups, and workspace preferences.',
      },
    },
    accountMenu: {
      ariaLabel: 'Open profile menu',
      settings: 'Settings',
      exportCrm: 'Export CRM Data',
      backup: 'Backup Data',
      signIn: 'Sign In',
      signInPlaceholder:
        'Sign in is coming soon. This account menu is ready for future authentication.',
      workspaceTitle: 'RepRoute Workspace',
      workspaceDescription:
        'No account is connected yet. This profile area is ready for future sign-in support.',
    },
    travelMode: {
      label: 'Travel mode',
      driving: 'Driving',
      walking: 'Walking',
    },
  },
  search: {
    eyebrow: 'Territory Search',
    heading: 'Find Prospects',
    prominentTitle: 'Find prospects',
    prominentDescription:
      'Run a Live Search by target industry and radius, then save qualified Prospects or add them to a Route.',
    marketLabel: 'City or market',
    marketPlaceholder: 'Optional city or market',
    marketHelp: 'Leave blank to search near your current location.',
    radiusLabel: 'Mileage radius',
    radiusOptions: [5, 10, 15, 25, 50] as const,
    radiusOptionLabels: {
      currentLocation: 'Use my current location',
      custom: 'Custom radius',
    },
    customRadiusLabel: 'Custom mileage radius',
    industriesLabel: 'Target industries',
    industriesPlaceholder: 'Select industries',
    industriesSelected: (count: number) =>
      count === 0
        ? 'Select industries'
        : count === 1
          ? '1 industry selected'
          : `${count} industries selected`,
    industryOptions: [
      'Construction',
      'Oil & Gas',
      'Equipment Rental',
      'HVAC',
      'Plumbing',
      'Electrical Contractors',
      'Manufacturing',
      'Warehousing & Logistics',
      'Automotive',
      'Agriculture',
      'Restaurants & Food Service',
      'Medical & Clinics',
      'Real Estate & Property Management',
      'Retail',
      'Industrial Supply',
      'Municipal & Government',
      'Data Centers',
      'Landscaping',
      'Roofing',
      'Fabrication & Welding',
    ] as const,
    searchButton: 'Search Businesses',
    searchingButton: 'Searching Businesses...',
    suggestedSearchesLabel: 'Suggested Searches',
    suggestedKeywords: [
      'equipment rental',
      'pipeline operators',
      'natural gas companies',
      'oilfield services',
      'industrial supply',
      'HVAC contractors',
      'electrical contractors',
      'plumbing contractors',
      'construction companies',
    ],
    statusHeading: 'Live Search Status',
    catalogHeading: 'Business Catalog',
    resultsEyebrow: 'Live Results',
    resultsHeading: 'Search Results',
    testButton: 'Test',
    openSettings: 'Open settings',
    selectedFiltersLabel: 'Selected Filters',
    filters: {
      radius: (miles: number) => `${miles} miles`,
      industries: (industries: string[]) => industries.join(', '),
      market: (market: string) => `Market: ${market}`,
      currentLocation: 'Current location',
    },
    location: {
      locating: 'Finding your current location...',
      ready: 'Using your current location as the default search center.',
      denied: 'Enable location access or enter a market manually.',
      unsupported: 'Location is unavailable in this browser. Enter a market manually.',
      marketOverride: (market: string) => `Using ${market} as the search center.`,
    },
    statusMessages: {
      liveResults: (count: number, summary: string) =>
        `Live Search returned ${count} business result${count === 1 ? '' : 's'} for ${summary}.`,
      noLiveResults: (summary: string) => `No business results found for ${summary}.`,
    },
    summary: {
      results: (count: number) => `${count} live result${count === 1 ? '' : 's'}`,
      error: 'Search error',
      resultsReturned: (count: number) => `${count} result${count === 1 ? '' : 's'} returned.`,
    },
    card: {
      badge: 'Live Search',
      searchResult: 'Search Result',
      save: 'Save Prospect',
      saved: 'Saved to Prospects',
      removeSaved: 'Remove Saved Prospect',
      removeProspect: 'Remove Prospect',
      addToRoute: 'Add to Route',
      inRoute: 'In Route',
      removeRoute: 'Remove from Route',
      openSaved: 'Open Saved',
      openInMaps: 'Open in Maps',
      navigateDrive: 'Navigate Drive',
      navigateWalk: 'Navigate Walk',
    },
    prospectCard: {
      removeFromSavedAria: 'Remove from Saved Prospects',
      saveProspectAria: 'Save Prospect',
      followUpPrefix: 'Follow-Up',
      notes: 'Notes',
      nextTouch: 'Next Touch',
      removeRoute: 'Remove from Route',
      manage: 'Manage',
      hide: 'Hide',
      priority: 'Priority',
      followUpDate: 'Follow-Up Date',
      clear: 'Clear',
      prospectNotes: 'Prospect Notes',
      editorHint: 'Edits save instantly to local storage on this device.',
    },
  },
  saved: {
    eyebrow: 'Saved Pipeline',
    heading: 'Saved Prospects',
    countLabel: (count: number) => `${count} saved`,
    savedMessage: 'Saved to Prospects',
    summaryPrimaryTitle: 'Keep the bench warm',
    summaryPrimaryDescription:
      'Saved Prospects stay available even when they are not on today’s Route.',
    summarySecondaryTitle: 'Notes stay attached',
    summarySecondaryDescription:
      'Every note, priority, and Follow-Up date is stored locally for future visits.',
    notesPreview: 'Notes Preview',
    notesPreviewEmpty: 'No notes added yet for this Prospect.',
    followUpStatus: 'Follow-Up Status',
    routeStatus: 'Route Status',
    routeStatusInRoute: 'In Today’s Route',
    routeStatusNotInRoute: 'Not in Route',
    lastVisited: 'Last Visited',
    lastVisitedEmpty: 'Not visited yet',
    edit: 'Edit',
    remove: 'Remove',
    openSaved: 'Open Saved',
    emptyAction: 'Browse Prospects',
  },
  routes: {
    suggestedKeywordCta: 'Find prospects',
    calculation: {
      eyebrow: 'Route Builder',
      heading: 'Calculate Route',
      description:
        'Finalize your selected stops and jump straight into Today’s Route without hunting for the Route tab.',
      button: 'Calculate Route',
      summaryHeading: 'Route Summary',
      emptyState: 'Add prospects to build a route.',
      singleStopHint: 'Add more stops to optimize a multi-stop route.',
      multiStopHint: 'Route ready. Review your stops and start navigating.',
      stopCount: (count: number) => `${count} stop${count === 1 ? '' : 's'}`,
      estimatedDrive: (time: string) => `Est. drive time: ${time}`,
      travelMode: (mode: string) => `Travel mode: ${mode}`,
      filters: (summary: string) => `Filters: ${summary}`,
    },
    routeSnapshotEyebrow: 'Today’s Route',
    routeSnapshotHeading: 'Route Snapshot',
    openRoute: 'Open Route',
    routeMapEyebrow: 'Live Route Map',
    routeMapHeading: 'Route Map',
    routeMapDescription:
      'Search results, Saved Prospects, and Route stops stay visible on the map while you work the day.',
    currentLocation: 'Your current location',
    todayListSummary: (count: number) => `${count} stops in today’s list`,
    navigateEntireRoute: 'Navigate Entire Route',
    clearRoute: 'Clear Route',
    mapSummary: {
      searchResults: (count: number) => `${count} search results`,
      savedProspects: (count: number) => `${count} Saved Prospects`,
      routeStops: (count: number) => `${count} Route stops`,
      visiblePins: (count: number) => `${count} visible pins`,
      routeMiles: (miles: string) => `${miles} total Route miles`,
      nearbySuggestions: (count: number) => `${count} nearby suggestions`,
    },
    stats: {
      routeStopsLabel: 'Today’s Route',
      routeStopsDetail: (miles: string) => `${miles} currently loaded into the Route`,
      completedStops: 'Completed Stops',
      completedStopsDetail: (remaining: number) => `${remaining} remaining on today’s Route`,
      estimatedDriveTime: 'Estimated Drive Time',
      estimatedDriveTimeDetail: (miles: string) => `${miles} currently planned`,
      completion: 'Completion',
      completionDetail: 'Progress across the active Route',
      nearbyProspects: 'Nearby Prospects',
      nearbyProspectsDetail: 'Within 5 miles of the current Route',
    },
    fieldWorkflowEyebrow: 'Field Workflow',
    fieldWorkflowHeading: 'Today’s Route',
    routeReady: 'Route ready',
    nextStop: (businessName: string) => `Next: ${businessName}`,
    currentStop: {
      eyebrow: 'Current Stop',
      heading: 'Current Stop',
      label: 'Current Stop',
      onLocation: 'You’re on location',
      enRoute: 'En route',
      tracking: 'Tracking your current location for arrival check-ins.',
      waiting: 'Waiting for a route location fix to start arrival detection.',
      locationDenied: 'Allow location access to trigger on-location prospect check-ins.',
      locationUnsupported: 'Arrival detection is unavailable in this browser.',
      locationError: 'RepRoute could not update your route location right now.',
      onLocationMessage: (businessName: string, distance: string) =>
        `You’re on location at ${businessName}. RepRoute detected you ${distance} from this stop.`,
      nearestMessage: (businessName: string, distance: string) =>
        `${businessName} is the closest stop at ${distance}.`,
      distanceAway: (distance: string) => `Distance away: ${distance}`,
      quickActions: {
        markCompleted: 'Mark Completed',
        markIncomplete: 'Mark Incomplete',
        saveProspect: 'Save Prospect',
        openSaved: 'Open Saved',
        editContactInfo: 'Edit Contact Info',
        addVisitNotes: 'Add Visit Notes',
        setFollowUp: 'Set Follow-Up',
        changePriority: 'Change Priority',
        addOutcomeTag: 'Add Outcome Tag',
      },
      contactFields: {
        contactName: 'Contact Name',
        contactTitle: 'Contact Title',
        phone: 'Phone',
        email: 'Email',
        website: 'Website',
        notes: 'Notes',
      },
    },
    currentFocusTitle: 'Current Focus',
    routeStopInfo: (order?: number) => `Route stop ${order ?? ''}`.trim(),
    stopLabel: (index: number) => `Stop ${index + 1}`,
    completed: 'Completed',
    markStopCompleteAria: 'Mark stop complete',
    markStopIncompleteAria: 'Mark stop incomplete',
    reorderStopAria: 'Reorder stop',
    actions: {
      callBusiness: 'Call Business',
      openWebsite: 'Open Website',
      navigateDrive: 'Navigate Drive',
      navigateWalk: 'Navigate Walk',
      remove: 'Remove',
      removeProspect: 'Remove Prospect',
      saveProspect: 'Save Prospect',
      openSaved: 'Open Saved',
      addNearbyProspect: 'Add Nearby Prospect',
      addToRoute: 'Add to Route',
    },
    removal: {
      heading: 'Remove Prospect',
      description:
        'Choose how to remove this Prospect. Notes, Follow-Ups, CRM export data, and visit history stay available on this device.',
      removeFromRoute: 'Remove from Route',
      removeFromSaved: 'Remove from Saved Prospects',
      cancel: 'Cancel',
    },
    visitOutcomeLabel: 'Visit Outcome',
    quickNoteLabel: 'Quick Note After Visit',
    quickNotePlaceholder: 'Capture what happened at this stop...',
    nearbyEyebrow: 'Nearby Coverage',
    nearbyHeading: 'Nearby Prospects',
    withinFiveMiles: 'Within 5 Miles',
    nearbyDistanceLabel: (distance: number) => `${distance.toFixed(1)} mi from Route`,
    outcomeTags: [
      'No Answer',
      'Decision Maker Met',
      'Follow-Up Needed',
      'Quote Opportunity',
      'Not Interested',
      'Bad Address',
      'Existing Customer',
    ] as const,
  },
  followUps: {
    noDate: 'No Follow-Up set',
    stats: {
      scheduled: 'Scheduled Follow-Ups',
      scheduledDetail: 'Every Follow-Up currently tracked on this device',
      dueNow: 'Due Now',
      dueNowDetail: 'Prospects that should be touched today or earlier',
      thisWeek: 'This Week',
      thisWeekDetail: 'Follow-Ups due within the next seven days',
    },
    openProspect: 'Open Prospect',
    savedStatus: 'Saved Prospect',
    unsavedStatus: 'Unsaved Prospect',
    nextFollowUp: 'Next Follow-Up',
    statuses: {
      dueNow: 'Due Now',
      tomorrow: 'Tomorrow',
      thisWeek: 'This Week',
      later: 'Later',
    },
  },
  settings: {
    appearanceTitle: 'Appearance',
    appearanceDescription: 'Switch between dark and light workspace themes.',
    darkMode: 'Dark mode',
    lightMode: 'Light mode',
    arrivalDetectionTitle: 'Arrival Detection Radius',
    arrivalDetectionDescription:
      'Choose how close you need to be before RepRoute marks a Route stop as on location.',
    arrivalDetectionLabel: 'Arrival Detection Radius',
    arrivalDetectionOption: (feet: number) =>
      feet >= 1320 ? '0.25 miles' : `${feet.toLocaleString()} feet`,
    googlePlacesEyebrow: 'Live Search',
    googlePlacesHeading: 'Search Connection',
    apiKeyDetected: 'API key detected',
    apiKeyMissing: 'API key missing',
    googlePlacesDescription:
      'Run a sample market search for “equipment rental Austin TX” to confirm live business results are loading.',
    testConnectionButton: 'Test Live Search',
    resultsReturned: (count: number) => `Results returned: ${count}`,
    errorDetails: (details: string) => `Error details: ${details}`,
    notifications: {
      eyebrow: 'Notifications',
      heading: 'Reminder Notifications',
      description:
        'Enable local browser reminders for Follow-Ups, today’s Route, and overdue Prospects. These alerts run on this device with no backend required.',
      localOnlyNote:
        'Notifications are local only. Keep RepRoute open in the browser or installed as a PWA for reminders to trigger without a server.',
      permissionPromptTitle: 'Allow Browser Notifications',
      permissionPromptDescription:
        'RepRoute needs notification permission before it can send local reminder alerts on mobile or desktop.',
      requestPermission: 'Enable Notifications',
      permissionStatusLabel: 'Permission Status',
      permissionStatuses: {
        granted: 'Allowed',
        denied: 'Blocked',
        default: 'Ask First',
        unsupported: 'Unsupported',
      },
      toggles: {
        enable: 'Enable Notifications',
        enableDescription: 'Allow RepRoute to send local reminder notifications on this device.',
        followUps: 'Follow-Up Alerts',
        followUpsDescription: 'Send a reminder when Prospects are due for a Follow-Up today.',
        route: 'Daily Route Reminder',
        routeDescription: 'Send a reminder for today’s Route so the day starts with the next stop in view.',
        overdue: 'Overdue Prospect Alerts',
        overdueDescription: 'Send a reminder when Follow-Ups have slipped past their scheduled date.',
      },
      timeLabel: 'Reminder Time',
      routeTimeLabel: 'Daily Route Reminder Time',
      followUpTimeLabel: 'Follow-Up Reminder Time',
      overdueTimeLabel: 'Overdue Prospect Alert Time',
      states: {
        on: 'On',
        off: 'Off',
      },
      messages: {
        permissionGranted: 'Browser notifications are enabled for this device.',
        permissionDenied:
          'Notification permission is blocked. Update your browser settings to re-enable alerts.',
        permissionUnsupported:
          'This browser does not support notifications, so local reminder alerts are unavailable.',
        notificationsDisabled: 'Local reminder notifications are turned off.',
        reminderDelivered: 'Reminder notifications are active and will fire at the times you selected.',
      },
      reminders: {
        followUpTitle: (count: number) =>
          `${count} Follow-Up${count === 1 ? '' : 's'} Due Today`,
        followUpBody: (names: string[]) =>
          names.length > 0
            ? `${names.join(', ')} ${names.length === 1 ? 'needs' : 'need'} attention today.`
            : 'You have Follow-Ups due today in RepRoute.',
        routeTitle: (count: number) => `Today’s Route Has ${count} Stop${count === 1 ? '' : 's'}`,
        routeBody: (nextStop: string | null) =>
          nextStop
            ? `Next stop: ${nextStop}. Open RepRoute to review the Route.`
            : 'Open RepRoute to review your Route for today.',
        overdueTitle: (count: number) =>
          `${count} Overdue Prospect${count === 1 ? '' : 's'} Need Attention`,
        overdueBody: (names: string[]) =>
          names.length > 0
            ? `${names.join(', ')} ${names.length === 1 ? 'is' : 'are'} overdue for Follow-Up.`
            : 'You have overdue Prospects waiting for Follow-Up.',
      },
    },
    storageEyebrow: 'Storage Status',
    storageHeading: 'Local-First Data',
    storageLocalTitle: 'Saved locally',
    storageLocalDescription:
      'Prospects, Saved Prospects, Route stops, notes, priorities, and dates stay on this device.',
    storageLiveTitle: 'Live search only',
    storageLiveDescription:
      'RepRoute relies on Live Search for business discovery and does not use fallback business data.',
    backupEyebrow: 'Data Backup',
    backupHeading: 'Data Backup',
    backupDescription:
      'Export a JSON snapshot of your local RepRoute data, or preview a backup before replacing current data on this device.',
    unknownExportDate: 'Unknown export date',
    exportJson: 'Export JSON',
    importJson: 'Import JSON',
    importPreviewEyebrow: 'Import Preview',
    readyToReplace: 'Ready to replace',
    replaceLocalData: 'Replace Local Data',
    cancel: 'Cancel',
    backupSummaryLabels: {
      realProspects: 'Prospects',
      savedProspects: 'Saved Prospects',
      routeStops: 'Route Stops',
      notes: 'Notes',
      priorityEdits: 'Priority Edits',
      followUps: 'Follow-Ups',
    },
    importWarning:
      'Confirming this import will replace the current RepRoute data stored on this device.',
  },
  crmExport: {
    eyebrow: 'CRM Export',
    heading: 'CRM Export',
    description:
      'Keep everything local for now. RepRoute maps your fields into CRM-ready CSV headers so direct API integrations can plug into the same profiles later.',
    exportFormatLabel: 'Export Format',
    exportScopeLabel: 'Export Scope',
    previewEyebrow: 'Preview',
    rowsLabel: (count: number) => `${count} row${count === 1 ? '' : 's'}`,
    recordsLabel: (count: number) => `${count} record${count === 1 ? '' : 's'}`,
    futureIntegrationsLabel: (targets: string[]) =>
      `Future direct integrations planned: ${targets.join(', ')}`,
    downloadLabel: (label: string) => `Download ${label}`,
    successMessage: (count: number, label: string) =>
      `Exported ${count} record${count === 1 ? '' : 's'} as ${label}.`,
    formats: {
      generic: 'CSV for Any CRM',
      hubspot: 'HubSpot-Ready CSV',
      salesforce: 'Salesforce-Ready CSV',
      zoho: 'Zoho-Ready CSV',
      pipedrive: 'Pipedrive-Ready CSV',
    },
    futureTargets: {
      generic: 'Generic CSV importer',
      hubspot: 'HubSpot',
      salesforce: 'Salesforce',
      zoho: 'Zoho',
      pipedrive: 'Pipedrive',
    },
    previewFallback: '—',
    scopes: {
      saved: 'Saved Prospects Only',
      route: 'Today’s Route Only',
      followups: 'Follow-Ups Only',
      all: 'All RepRoute Data',
    },
  },
  errors: {
    apiErrorLabel: 'API Error',
    searchMissingFields: 'Select at least one target industry before running a Live Search.',
    searchMissingFieldsDetail:
      'Live Search needs at least one target industry to return targeted business results.',
    searchFailedDetail: 'Live Search failed. Review the response and try again.',
    connectGooglePlaces: 'Enable Live Search to find businesses.',
    connectGooglePlacesDetail: 'Add a valid search API key to load live business results.',
    locationRequired: 'Enable location access or enter a market manually.',
    mapApiKeyMissing: 'Map key missing',
    mapFailedToLoad: 'Map failed to load',
    loadingMap: 'Loading map...',
    noRatingYet: 'No rating yet',
    websiteUnavailable: 'Website unavailable',
    googlePlacesConnectionRunning: 'Testing Live Search with “equipment rental Austin TX”...',
    googlePlacesConnectionSucceeded: 'Live Search connection succeeded.',
    googlePlacesConnectionFailed: 'Live Search connection failed.',
    noCrmDataForScope: 'No Prospects are available for that CRM Export scope yet.',
    crmExportFailed: 'RepRoute could not generate that CRM Export CSV.',
    backupExportFailed: 'RepRoute could not export a backup file.',
    backupReadFailed: 'RepRoute could not read that backup file.',
    backupLoaded: 'Backup loaded. Review the preview before replacing local data.',
    backupExported: 'RepRoute data exported as a JSON backup.',
    backupImported: (fileName: string) =>
      `Imported ${fileName}. Existing local RepRoute data was replaced.`,
  },
  emptyStates: {
    noRealProspectsTitle: 'No Prospects Loaded Yet',
    noRealProspectsCopy: 'Enable Live Search to find businesses.',
    noRouteTitle: 'No prospects currently in your route.',
    noRouteCopy: 'Add Prospects from Search or Saved Prospects to build today’s Route.',
    noNearbyTitle: 'No Nearby Prospects Yet',
    noNearbyCopy:
      'Search more businesses to surface nearby suggestions within 5 miles of your Route.',
    noSavedTitle: 'No Saved Prospects Yet',
    noSavedCopy: 'Save a Prospect to keep it ready for a future Route or Follow-Up.',
    noHotProspectsTitle: 'No Hot Prospects Yet',
    noHotProspectsCopy:
      'Use Search to qualify businesses and mark the best opportunities as Hot.',
    noFollowUpsTitle: 'No Follow-Ups Scheduled',
    noFollowUpsCopy:
      'Use the Manage panel on any Prospect to schedule a Follow-Up and it will appear here.',
    noCrmDataTitle: 'No CRM Export Data For This Scope',
    noCrmDataCopy:
      'Search and save Prospects, add them to a Route, or schedule Follow-Ups before exporting.',
    noSearchResultsTitle: 'No Businesses Found',
    noSearchResultsCopy: 'No businesses found. Try a different keyword or location.',
    googlePlacesSearchFailedTitle: 'Live Search Failed',
    connectGooglePlacesTitle: 'Enable Live Search',
    noRouteLoadedTitle: 'No prospects currently in your route.',
    noRouteLoadedCopy:
      'Add Prospects from Search or Saved Prospects to build today’s Route.',
  },
} as const

export type UiText = typeof uiText
